---
# file: roles/filebeat/tasks/main.yml
- name: register subscription and yum proxy setting
  import_tasks: yum_setup.yml

- block:
  - name: enable elastic repo
    copy:
      src: elastic.repo
      dest: /etc/yum.repos.d/elastic.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_elastic_repo_setting

  - name: filebeat install
    package:
      name: filebeat
      state: latest
    register: result
    until: result is success
    retries: 3
    delay: 5

  - name: filebeat setting
    template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_filebeat_setting
    notify: filebeat restart

  - name: filebeat auditd setting
    copy:
      src: auditd.yml
      dest: /etc/filebeat/modules.d/auditd.yml
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_filebeat_auditd_setting
    notify: filebeat restart

  - name: filebeat kibana setting
    copy:
      src: kibana.yml
      dest: /etc/filebeat/modules.d/kibana.yml
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_filebeat_kibana_setting
    notify: filebeat restart

  - name: filebeat custom postgresql modules setting
    include_tasks: module.yml
    vars:
      - module:
        - src: 'custom_postgresql.yml'
          path: '/etc/filebeat/modules.d'
          owner: 'root'
          group: 'root'
          mode: '0644'
      - directory:
        - path: '/usr/share/filebeat/module/custom_postgresql'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_postgresql/log'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_postgresql/log/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_postgresql/log/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
      - file:
        - src: 'custom_postgresql/module.yml'
          path: '/usr/share/filebeat/module/custom_postgresql'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_postgresql/log/manifest.yml'
          path: '/usr/share/filebeat/module/custom_postgresql/log'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_postgresql/log/config/log.yml'
          path: '/usr/share/filebeat/module/custom_postgresql/log/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_postgresql/log/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_postgresql/log/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'

  always:
  - name: filebeat common backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_elastic_repo_setting|default() }}"
      - "{{ is_filebeat_setting|default() }}"
      - "{{ is_filebeat_auditd_setting|default() }}"
      - "{{ is_filebeat_kibana_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable filebeat service
  service:
    name: filebeat.service
    state: started
    enabled: yes
    daemon_reload: yes
