---
# file: roles/filebeat/tasks/main.yml
- name: register subscription and yum proxy setting
  import_tasks: yum_setup.yml

- block:
  - name: enable elastic repo
    copy:
      src: elastic.repo
      dest: /etc/yum.repos.d/elastic.repo
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_elastic_repo_setting

  - name: filebeat install
    package:
      name: filebeat
      state: latest
    register: result
    until: result is success
    retries: 3
    delay: 5

  - name: filebeat setting
    template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_filebeat_setting
    notify: filebeat restart

  - name: filebeat fields setting
    copy:
      src: fields.yml
      dest: /etc/filebeat/fields.yml
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_filebeat_fields_setting
    notify: filebeat restart

  - name: filebeat auditd setting
    copy:
      src: auditd.yml
      dest: /etc/filebeat/modules.d/auditd.yml
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_filebeat_auditd_setting
    notify: filebeat restart

  - name: filebeat kibana setting
    copy:
      src: kibana.yml
      dest: /etc/filebeat/modules.d/kibana.yml
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_filebeat_kibana_setting
    notify: filebeat restart

  - name: filebeat delete disable setting
    file:
      path: "{{ item }}"
      state: absent
    notify: filebeat restart
    with_items:
      - /etc/filebeat/modules.d/auditd.yml.disabled
      - /etc/filebeat/modules.d/kibana.yml.disabled

  - name: filebeat custom system modules setting
    include_tasks: module.yml
    vars:
      - module:
        - src: 'custom_system.yml'
          path: '/etc/filebeat/modules.d'
          owner: 'root'
          group: 'root'
          mode: '0644'
      - directory:
        - path: '/usr/share/filebeat/module/custom_system'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/syslog'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/syslog/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/syslog/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/auth'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/auth/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/auth/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/mail'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/mail/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_system/mail/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
      - file:
        - src: 'custom_system/module.yml'
          path: '/usr/share/filebeat/module/custom_system'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/syslog/manifest.yml'
          path: '/usr/share/filebeat/module/custom_system/syslog'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/syslog/config/syslog.yml'
          path: '/usr/share/filebeat/module/custom_system/syslog/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/syslog/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_system/syslog/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/auth/manifest.yml'
          path: '/usr/share/filebeat/module/custom_system/auth'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/auth/config/auth.yml'
          path: '/usr/share/filebeat/module/custom_system/auth/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/auth/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_system/auth/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/mail/manifest.yml'
          path: '/usr/share/filebeat/module/custom_system/mail'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/mail/config/mail.yml'
          path: '/usr/share/filebeat/module/custom_system/mail/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_system/mail/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_system/mail/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'

  - name: filebeat custom postgresql modules setting
    include_tasks: module.yml
    vars:
      - module:
        - src: 'custom_postgresql.yml'
          path: '/etc/filebeat/modules.d'
          owner: 'root'
          group: 'root'
          mode: '0644'
      - directory:
        - path: '/usr/share/filebeat/module/custom_postgresql'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_postgresql/log'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_postgresql/log/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_postgresql/log/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
      - file:
        - src: 'custom_postgresql/module.yml'
          path: '/usr/share/filebeat/module/custom_postgresql'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_postgresql/log/manifest.yml'
          path: '/usr/share/filebeat/module/custom_postgresql/log'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_postgresql/log/config/log.yml'
          path: '/usr/share/filebeat/module/custom_postgresql/log/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_postgresql/log/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_postgresql/log/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'

  - name: filebeat custom apache2 modules setting
    include_tasks: module.yml
    vars:
      - module:
        - src: 'custom_apache2.yml'
          path: '/etc/filebeat/modules.d'
          owner: 'root'
          group: 'root'
          mode: '0644'
      - directory:
        - path: '/usr/share/filebeat/module/custom_apache2'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_apache2/access'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_apache2/access/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_apache2/access/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_apache2/error'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_apache2/error/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_apache2/error/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
      - file:
        - src: 'custom_apache2/module.yml'
          path: '/usr/share/filebeat/module/custom_apache2'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_apache2/access/manifest.yml'
          path: '/usr/share/filebeat/module/custom_apache2/access'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_apache2/access/config/access.yml'
          path: '/usr/share/filebeat/module/custom_apache2/access/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_apache2/access/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_apache2/access/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_apache2/error/manifest.yml'
          path: '/usr/share/filebeat/module/custom_apache2/error'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_apache2/error/config/error.yml'
          path: '/usr/share/filebeat/module/custom_apache2/error/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_apache2/error/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_apache2/error/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'

  - name: filebeat custom tomcat modules setting
    include_tasks: module.yml
    vars:
      - module:
        - src: 'custom_tomcat.yml'
          path: '/etc/filebeat/modules.d'
          owner: 'root'
          group: 'root'
          mode: '0644'
      - directory:
        - path: '/usr/share/filebeat/module/custom_tomcat'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_tomcat/access'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_tomcat/access/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_tomcat/access/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
      - file:
        - src: 'custom_tomcat/module.yml'
          path: '/usr/share/filebeat/module/custom_tomcat'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_tomcat/access/manifest.yml'
          path: '/usr/share/filebeat/module/custom_tomcat/access'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_tomcat/access/config/access.yml'
          path: '/usr/share/filebeat/module/custom_tomcat/access/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_tomcat/access/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_tomcat/access/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'

  - name: filebeat custom gclog modules setting
    include_tasks: module.yml
    vars:
      - module:
        - src: 'custom_gclog.yml'
          path: '/etc/filebeat/modules.d'
          owner: 'root'
          group: 'root'
          mode: '0644'
      - directory:
        - path: '/usr/share/filebeat/module/custom_gclog'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_gclog/log'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_gclog/log/config'
          owner: 'root'
          group: 'root'
          mode: '0755'
        - path: '/usr/share/filebeat/module/custom_gclog/log/ingest'
          owner: 'root'
          group: 'root'
          mode: '0755'
      - file:
        - src: 'custom_gclog/module.yml'
          path: '/usr/share/filebeat/module/custom_gclog'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_gclog/log/manifest.yml'
          path: '/usr/share/filebeat/module/custom_gclog/log'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_gclog/log/config/log.yml'
          path: '/usr/share/filebeat/module/custom_gclog/log/config'
          owner: 'root'
          group: 'root'
          mode: '0644'
        - src: 'custom_gclog/log/ingest/pipeline.json'
          path: '/usr/share/filebeat/module/custom_gclog/log/ingest/'
          owner: 'root'
          group: 'root'
          mode: '0644'

  always:
  - name: filebeat common backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_elastic_repo_setting|default() }}"
      - "{{ is_filebeat_setting|default() }}"
      - "{{ is_filebeat_fields_setting|default() }}"
      - "{{ is_filebeat_auditd_setting|default() }}"
      - "{{ is_filebeat_kibana_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: enable filebeat service
  service:
    name: filebeat.service
    state: started
    enabled: yes
    daemon_reload: yes
