module_version: 1.0

var:
  - name: paths
    default:
      - /var/log/tomcat8/localhost_access_log*txt

ingest_pipeline: ingest/pipeline.json
input: config/access.yml

requires.processors:
- name: geoip
  plugin: ingest-geoip
